import { VitePWAOptions } from 'vite-plugin-pwa';

// you can copy the base structure of manifest object.
export const manifestForPlugin: Partial<VitePWAOptions> = {
  registerType: 'prompt',
  includeAssets: [
    'favicon.ico',
    'apple-touch-icon.png',
    'villains/Captain_Hook.webp',
    'villains/Cruella_De_Vil.webp',
    'villains/Dr_Facilier.webp',
    'villains/Evil_Queen.webp',
    'villains/Gaston.webp',
    'villains/Hades.webp',
    'villains/Horned_King.webp',
    'villains/Jafar.webp',
    'villains/King_Candy.webp',
    'villains/Lady_Tremaine.webp',
    'villains/Lotso.webp',
    'villains/Madam_Mim.webp',
    'villains/Maleficent.webp',
    'villains/Mother_Gothel.webp',
    'villains/Oogie_Boogie.webp',
    'villains/Pete.webp',
    'villains/Prince_John.webp',
    'villains/Queen_of_Hearts.webp',
    'villains/Ratigan.webp',
    'villains/Scar.webp',
    'villains/Shere_Khan.webp',
    'villains/Syndrome.webp',
    'villains/Ursula.webp',
    'villains/Yzma.webp',
  ],
  manifest: {
    name: 'Villainous Tokens',
    short_name: 'Villainous Tokens',
    description: 'Token counter for VIllainous board game',
    icons: [
      {
        src: 'pwa-64x64.png',
        sizes: '64x64',
        type: 'image/png',
      },
      {
        src: 'pwa-192x192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: 'pwa-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: 'maskable-icon-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
    theme_color: '#0a0a0a',
    background_color: '#171717',
    display: 'standalone',
    scope: '/',
    start_url: '/',
    orientation: 'portrait',
  },
};
