import { VitePWAOptions } from 'vite-plugin-pwa';

// you can copy the base structure of manifest object.
export const manifestForPlugin: Partial<VitePWAOptions> = {
  registerType: 'prompt',
  includeAssets: [
    'favicon.ico',
    'apple-touch-icon.png',
    'masked-icon.svg',
    'Captain_Hook.png',
    'Cruella_De_Vil.png',
    'Dr_Facilier.png',
    'Evil_Queen.png',
    'Gaston.png',
    'Hades.png',
    'Horned_King.png',
    'Jafar.png',
    'King_Candy.png',
    'Lady_Tremaine.png',
    'Lotso.png',
    'Madam_Mim.png',
    'Maleficent.png',
    'Mother_Gothel.png',
    'Oogie_Boogie.png',
    'Pete.png',
    'Prince_John.png',
    'Queen_of_Hearts.png',
    'Ratigan.png',
    'Scar.png',
    'Shere_Khan.png',
    'Syndrome.png',
    'Ursula.png',
    'Yzma.png',
  ],
  manifest: {
    name: 'Villainous Tokens Counter',
    short_name: 'Tokens Counter',
    description: 'I am a simple vite app',
    icons: [
      {
        src: '/android-chrome-192x192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: '/android-chrome-512x512.png',
        sizes: '512x512',
        type: 'image/png',
      },
      {
        src: '/apple-touch-icon.png',
        sizes: '180x180',
        type: 'image/png',
        purpose: 'apple touch icon',
      },
      {
        src: '/maskable-icon.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any maskable',
      },
    ],
    theme_color: '#0a0a0a',
    background_color: '#171717',
    display: 'standalone',
    scope: '/',
    start_url: '/',
    orientation: 'portrait',
  },
};
